### ISSUE TITLE
Widget: depicted by

### ISSUE THREAD

**Issue by rombaum** [ts4nfdi/terminology-service-suite#104]
It would be great to create a widget to show images. I just spotted an [image](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001443?lang=en) at EMBL-EBIs instance. It should be very simple to create a widget out of it and integrate this one to multiple other widgets.

![grafik](https://github.com/ts4nfdi/terminology-service-suite/assets/47030738/e850d88f-0f9f-4955-9ff0-9e62fd7e55c4)

**Comment by Pooya-Oladazimi** [comment]
I think it can be a new tab here: https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/docs/react_metadatawidget--docs

and make it optional (show the image tab or not).

**Comment by rombaum** [comment]
> I think it can be a new tab here: https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/docs/react_metadatawidget--docs

This could be one place where to integrate a standalone widget. It would be also possible to add this here as well:

https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/story/react_entityinfowidget--term-info-widget

I also have in mind it could be helpful to provide a page with the collection of all images for a specific terminology.
