### ISSUE TITLE
Implementation of functions is not shown correctly in React Storybook

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/terminology-service-suite#137]
See start of discussion for 1) in https://github.com/ts4nfdi/terminology-service-suite/issues/136

**Comment by VincentKneip** [comment]
After a bit of research, the support for function parameters in Storybook is not very high. I discovered one possibility though:

__Transforms function__ - see [here](https://storybook.js.org/docs/api/doc-blocks/doc-block-source#transform)
In the `{...}.stories.tsx` file of a widget, you can modify the displayed source code with a `transform` function, which obtains the current code string and the `StoryContext` object providing information of the current story, e.g. the current `args` values. Sadly, as functions are not greatly supported under Storybook, the values for the onNavigate-functions are __missing__ in the `args` object. 

![grafik](https://github.com/user-attachments/assets/d463b1bf-34c6-433a-a690-6723ebe9e876)
_EntityRelationsWidget.stories.tsx_

__ArgType mapping__ - see [here](https://storybook.js.org/docs/writing-stories/args#mapping-to-complex-arg-values)
However, there could be a workaround for this: Story argTypes support a mapping option with which simple strings could be mapped to specific function implementations. This leads to these string values now __appearing__ in the `args` object. These string values can now be used by the `transform` function to be mapped to a string of the function implementation and be embedded in the `code` string:

![grafik](https://github.com/user-attachments/assets/186be047-9045-4be6-9cda-e2039e619629)
_EntityRelationsWidget.stories.tsx_

This has the following result in Storybook:
![grafik](https://github.com/user-attachments/assets/bf2bc145-72ca-4737-add6-2f77a09ed477)

@jusa3 what do you think if this?

**Comment by VincentKneip** [comment]
Pushed a commit on `feat/on-navigate-entity-info-relations` implementing this approach. Here's how it looks like:
![grafik](https://github.com/user-attachments/assets/3959649d-0551-4656-a508-43003c67a15e)
_figure 1_

![grafik](https://github.com/user-attachments/assets/8db4956f-2a88-42a8-97b9-99419e776b68)
_figure 2_
