### ISSUE TITLE
IriWidget: flexible copy button needed

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/terminology-service-suite#154]
Need flexible copy button (on the left or on the right side of the text).

![image](https://github.com/user-attachments/assets/70816ef3-474c-4231-abb1-86d90926fceb)

I see two options:
- change the boolean type of copyButton to string or to "left" | "right" | "none" -> would be a breaking change
- add another parameter such as copyButtonPosition -> would be a new feature

What do you think @rombaum @Pooya-Oladazimi ?

**Comment by Pooya-Oladazimi** [comment]
@jusa3 

I prefer the new feature (second).

**Comment by Pooya-Oladazimi** [comment]
@jusa3 

I have some confusion about this. Which widget we are talking about? The screenshot does not look like the Title widget.

**Comment by jusa3** [comment]
You're right, sorry. The screenshot is from the Terminology Service that uses the Iri Widget.

**Comment by Pooya-Oladazimi** [comment]
@jusa3 

Thanks. I changed my mind and went with the first approach to avoid introducing a new input parameter.
