### ISSUE TITLE
Are all hierarchy widgets still necessary?

### ISSUE THREAD

**Issue by VincentKneip** [ts4nfdi/terminology-service-suite#158]
Are all three implementations of a hierarchy widget (HierarchyWidgetOLS, HierarchyWidgetDeprecated, HierarchyWidget) still needed ore can we remove some of them?

Especially, should the new HierarchyWidget be used in Metadatawidget now?

@rombaum @jusa3

**Comment by jusa3** [comment]
HierarchyWidgetOLS and HierarchyWidgetDeprecated can be removed -> it's a breaking change! Do two commits, one removing each widget with following commit messages:
"BREAKING CHANGE: The HierarchyWidgetOLS is deprecated and has been removed."

Yes, the new HierarchyWidget should be used in the MetadataWidget. Remember to pass needed parameters and give them meaningful names.

**Comment by VincentKneip** [comment]
Linked a pull request to review @jusa3.
