### ISSUE TITLE
GraphViewWidget: Is parameter useLegacy necessary?

### ISSUE THREAD

**Issue by VincentKneip** [ts4nfdi/terminology-service-suite#160]
The GraphViewWidget contains a `useLegacy` parameter, but it doesn't seem to be used. Should the parameter be removed?

@Pooya-Oladazimi

**Comment by Pooya-Oladazimi** [comment]
@VincentKneip 

The parameter is currently not used since ols4 v2 does not provide any graph endpoint and the EBI is still using ols3 (ols4 v1). I was not sure that this would be the case in the future so I kept this option open. But you are right, we can remove it from the story inputs at least.

**Comment by VincentKneip** [comment]
All right. I will create a branch addressing a couple of minor issues soon, and deal with this issue there.

**Comment by VincentKneip** [comment]
Merged with #162
