### ISSUE TITLE
confusion regading the description widget

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [ts4nfdi/terminology-service-suite#169]
The description widget at the moment is just accept an input text and renders it:

```
function DescriptionPresentation(props: DescriptionPresentationProps) {
  const {descText, description, ...rest} = props;

  return (
    <>
      <EuiText {...rest}>{descText || description}</EuiText>
    </>
  );
}
```

- there is no difference between this and the EuiText 
- the widget should accept a term iri and shows it description by fetching the term. currently is a text widget rather description. The  problem is this way the user need to parse the term and extract the description before using this widget which kind of question the intention behind using it in general. 

@jusa3 @VincentKneip what do you think?

**Comment by jusa3** [comment]
This is the DescriptionPresentation component. It is not a widget. It's purpose is to render the text for the DescriptionWidget. The DescriptionPresentation is used in the MetadataWidget to avoid multiple requests.

The DescriptionWidget does exactly as you described, see https://github.com/ts4nfdi/terminology-service-suite/blob/main/src/components/widgets/MetadataWidget/DescriptionWidget/DescriptionWidget.tsx#L23

**Comment by Pooya-Oladazimi** [comment]
@jusa3 
aha thanks. I got confused.
