### ISSUE TITLE
Breaking changes are not released properly

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/terminology-service-suite#171]
I've noticed that a breaking change comment in the header of a commit message is not resolved by the semantic-release plugin. The comment needs to be in the footer.

**Comment by jusa3** [comment]
@Pooya-Oladazimi @VincentKneip @rombaum 

Please read and follow the commit message rules in the readme to improve our automatically generated documentation :)

https://github.com/ts4nfdi/terminology-service-suite?tab=readme-ov-file#commit-message-formatting

**Comment by Pooya-Oladazimi** [comment]
@jusa3 

what if we create a commit message template for this repository like: https://gist.github.com/mohit-raj-purohit/1b59c879f26d7f6b6546753d32a9ebf1#creating-a-git-commit-message-template
