### ISSUE TITLE
IriWidget: Remove unnecessary "parameter" property

### ISSUE THREAD

**Issue by VincentKneip** [ts4nfdi/terminology-service-suite#65]
The `parameter`-property is included, but not used within the IriWidget (see [here](https://github.com/nfdi4health/semlookp-widgets/blob/main/src/components/widgets/MetadataWidget/IriWidget/IriWidget.tsx)).

Can it therefore be removed from the property object type `IriWidgetProps`?

**Comment by rombaum** [comment]
I didn't see a point at the moment why we should need the `parameter`-property there. So it could be removed.

**Comment by VincentKneip** [comment]
Removed the property in [this](https://github.com/nfdi4health/semlookp-widgets/commit/c25a198953d67ebbe09ed41c79643ca95a7ed2b1) commit. When `feat/plainJS-sb-integration` is merged, this issue can be closed
