### ISSUE TITLE
Update EUI to the latest version (or v88 since EuiSuggest was removed in v89)

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/terminology-service-suite#80]
The semlookp widgets are not compatible with the latest EUI version (v94). In v89, EuiSuggest was removed (https://github.com/elastic/eui/releases/tag/v89.0.0). It should be possible to update to v88.

Perhaps we can create a wrapper for each widget, as is the case for the SearchBarWidget and update to the latest EUI version.

We should update the README to inform about using the widgets with EUI version < 88.

**Comment by johannes-darms** [comment]
What are your plans on upgrading the UI kit?

**Comment by jusa3** [comment]
We have a bigger problem with the eui styles overriding the consuming app styles:
https://github.com/ts4nfdi/terminology-service-suite/issues/144
https://github.com/ts4nfdi/terminology-service-suite/pull/156

There is no solution yet. We are considering using another design library. @johannes-darms

**Comment by johannes-darms** [comment]
Have you tried out this option: https://eui.elastic.co/v97.3.1/#/utilities/provider#theming-and-global-styles
