### ISSUE TITLE
Part icon is missing in ols4 hierarchy widget

### ISSUE THREAD

**Issue by rombaum** [ts4nfdi/terminology-service-suite#95]
The `p` in the ols4 based hierarchy widget is missing in our [widget](https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/story/react_metadatawidget--ols-4-v-2). 

I used **_milk_** from the ontology **_uberon_** as an example and saw that the p is missing in the hierarchy.

![grafik](https://github.com/ts4nfdi/terminology-service-suite/assets/47030738/20bd4c35-34a6-4937-91d0-65928ec1093a)

It is working for the hierarchy at the instance of EMBL-EBI: https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001913

**Comment by VincentKneip** [comment]
The `p` icon is an SVG-image called `part.svg`, which should be provided at `"{process.env.PUBLIC_URL!}/part.svg"` (see [here](https://github.com/zbmed/ols4/blob/dev-hierarchy-widget/frontend/src/pages/ontologies/entities/EntityTree.tsx#L276)).
At EMBL-EBI, there is a corresponding image provided at https://www.ebi.ac.uk/ols4/part.svg. However, for our project, `process.env.PUBLIC_URL!` does not seem to match `"https://www.ebi.ac.uk/ols4/"`.

A quick fix would be to change the line inside `EntityTree.tsx` in the `ols4`-project mentioned above from
`src={urlJoin(process.env.PUBLIC_URL!, "/part.svg")}`
to
`src={"https://www.ebi.ac.uk/ols4/part.svg"}`
