### ISSUE TITLE
make breadcrumb interactive

### ISSUE THREAD

**Issue by rombaum** [ts4nfdi/terminology-service-suite#96]
I had a look to the entitypage of SemLookP new user interface. I wanted to switch from a class page to a ontology page by clicking on the class (e.g. uberon in the screenshot) in the breadcrumb. this could be solved by adding a parameter such as _**targetLink**_ in the [SearchResultListWidget](https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/docs/html_searchresultslistwidget--docs).

![grafik](https://github.com/ts4nfdi/terminology-service-suite/assets/47030738/7fedf0ee-33c1-4e08-afcc-ff6fd1330f35)

**Comment by jusa3** [comment]
perfectly solved with #133
