### ISSUE TITLE
Not all breaking changes are documented (updating 1.9 -> 2.1.0)

### ISSUE THREAD

**Issue by vera** [ts4nfdi/terminology-service-suite#99]
I just updated from v1.9 to v2.1. The only breaking change that is documented for the update to 2.x is the new name and repo URL. However, I also found the following changes that broke my existing code:

* TitleWidget renamed its param `entityType` to `thingType`
* AutocompleteWidget renamed its param `selectOption` to `preselected` (also, it now expects an array of pre-selected options instead of a single option)
* AutocompleteWidget changes its param `selectionChangedEvention` to expect a function that deals with an array of selected options instead of a single option

Maybe this could be added to the list of breaking changes included in 2.0, since that is most likely where people will check when updating the package. (even though the changes were probably actually made in other versions)

For future versions, it would be good if all changes to the interface (param names and types) would be marked as breaking.

**Comment by jusa3** [comment]
Sorry for the trouble and thanks for reporting! Added the mentioned breaking changes and a developer note to the readme.

**Comment by vera** [comment]
Thank you!
